### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by waseem-polus** [waseem-polus/wui-design#96]
- [x] Combine installation and getting started into one page
- [x] Add introduction page with information on vision and goals of the library (moved to #118 )
- [x] Document how components can be styled with tw, css classnames, and inline ``style`` prop (moved to #119 )
- [x] Lucide icons are used in some components (moved to #119 )
- [x] Remove un-refined/undocumented component pages
- [x] Update greenhouse page
- [x] Remove spacing and colors sections since they're not used anymore
